---
- name: Install nginx
  become: true
  apt:  pkg=nginx state=latest

- name: Change nginx user
  become: true
  lineinfile: dest=/etc/nginx/nginx.conf regexp='^user ' line="user {{ ansible_ssh_user }};"
  notify: restart nginx

- name: Ensure nginx log directory exists
  file: dest=/var/log/nginx/symfony state=directory

- name: Change default nginx site
  become: true
  template: src=default.tpl dest=/etc/nginx/sites-available/default
  notify: restart nginx
