test:
  image: mroca/symfony-test
  variables:
    SYMFONY_ENV: test
  before_script:
    - export COMPOSER_CACHE_DIR=/cache/composer
    - php composer.phar install --no-interaction --no-progress --prefer-dist
  script:
    - vendor/bin/phpunit -c .

deploy:
  type: deploy
  image: ruby
  script:
    - gem install dpl
    - dpl --provider=heroku --app=ecpshows --api-key=$API_KEY
