test:
  image: mroca/symfony-test
  tags:
    - all
  variables:
    SYMFONY_ENV: test
  before_script:
    - apt-get update -q
    - apt-get install -y -q php5-sqlite
    - export COMPOSER_CACHE_DIR=/cache/composer
    - php composer.phar install --no-interaction --no-progress --prefer-dist
  script:
    - vendor/bin/phpunit -c .

deploy:
  type: deploy
  tags:
    - all
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=ecpshows --api-key=$API_KEY
