# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    passwordListener:
        class: AppBundle\EventListener\PasswordEncoderListener
        arguments: ["@security.password_encoder"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    myshows.rest_api_caller:
        class: AppBundle\API\RESTAPICaller
        arguments: ["@guzzle.client.api_tvmaze"]
    myshows.fetcher.shows:
        class: AppBundle\Fetcher\ShowsFetcher
        arguments: ["@myshows.rest_api_caller"]
