# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    password_listener:
        class: AppBundle\EventListener\PasswordEncoderListener
        arguments: ["@security.password_encoder"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    myshows.rest_api_caller:
        class: AppBundle\API\RESTAPICaller
        arguments: ["@guzzle.client.api_tvmaze"]
    myshows.fetcher.shows:
        class: AppBundle\Fetcher\ShowsFetcher
        arguments: ["@myshows.rest_api_caller", "%placeholder_url%"]
    form.type.user:
        class: AppBundle\Form\UserType
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: form.type, alias: user_type }
    myshows.captcha_validator:
        class: AppBundle\Form\CaptchaValidator
        arguments: ["@session", "%captcha_secret%"]